import { Department, Doctor, HealthPackage, BlogArticle } from '../types';

export const BRAND_NAME = 'MEDOCYN HEALTHCARE';
export const BRAND_TAGLINE = 'Advancing Healthcare Through Technology';

export const CONTACT_INFO = {
  phone: '+1 (800) 555-0199',
  emergencyPhone: '+1 (800) 555-9111',
  email: 'contact@medocyn.com',
  address: '100 Medical Center Parkway, Suite 500, Metro City, MC 12345',
  hours: '24/7 Emergency Care | Outpatient: Mon-Sat 8:00 AM - 8:00 PM',
};

export const DEPARTMENTS: Department[] = [
  {
    id: 'dept-gen-med',
    name: 'General Medicine',
    slug: 'general-medicine',
    description: 'Comprehensive primary care, disease prevention, health education, and management of chronic illnesses by expert general practitioners.',
    icon: 'Activity',
    specialties: ['Preventive Care', 'Chronic Disease Management', 'Immunizations', 'Annual Physicals'],
  },
  {
    id: 'dept-cardiology',
    name: 'Cardiology',
    slug: 'cardiology',
    description: 'Advanced cardiovascular care specializing in diagnostic testing, heart disease prevention, coronary interventions, and rhythm management.',
    icon: 'Heart',
    specialties: ['Coronary Care', 'Echocardiography', 'Arrhythmia Management', 'Preventive Cardiology'],
  },
  {
    id: 'dept-pediatrics',
    name: 'Pediatrics',
    slug: 'pediatrics',
    description: 'Specialized healthcare for infants, children, and adolescents, covering wellness checkups, growth monitoring, and acute care.',
    icon: 'Baby',
    specialties: ['Newborn Care', 'Developmental Screening', 'Pediatric Immunology', 'Adolescent Medicine'],
  },
  {
    id: 'dept-orthopedics',
    name: 'Orthopedics',
    slug: 'orthopedics',
    description: 'Expert treatment for musculoskeletal conditions, including sports injuries, joint replacements, spine care, and rehabilitative therapy.',
    icon: 'Bone',
    specialties: ['Joint Replacement', 'Sports Medicine', 'Spine Care', 'Fracture Management'],
  },
  {
    id: 'dept-neurology',
    name: 'Neurology',
    slug: 'neurology',
    description: 'Highly specialized diagnostics and therapeutics for disorders of the central and peripheral nervous systems.',
    icon: 'Brain',
    specialties: ['Stroke Management', 'Epilepsy Care', 'Neuropathy Treatment', 'Sleep Medicine'],
  },
  {
    id: 'dept-womens-health',
    name: 'Women\'s Health',
    slug: 'womens-health',
    description: 'Empathetic and complete gynecological, obstetric, and reproductive healthcare services for every stage of a woman\'s life.',
    icon: 'Venus',
    specialties: ['Obstetrics', 'Gynecology', 'Fertility Support', 'Menopause Care'],
  },
];

export const HEALTH_PACKAGES: HealthPackage[] = [
  {
    id: 'pkg-essential',
    name: 'Essential Wellness Package',
    slug: 'essential-wellness',
    tagline: 'Basic preventative screening for individuals',
    price: 199,
    discountPrice: 149,
    description: 'An essential health checkup recommended annually for early detection of potential metabolic, cardiac, or systemic disorders.',
    features: [
      'Complete Blood Count (CBC) with ESR',
      'Fasting Blood Glucose',
      'Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)',
      'Kidney Function Test (Creatinine, BUN)',
      'Liver Function Test (ALT, AST, Bilirubin)',
      'General Physician Consultation (15-min)',
    ],
    idealFor: 'Individuals aged 18-35 looking for a routine baseline checkup.',
  },
  {
    id: 'pkg-executive',
    name: 'Executive Health Screening',
    slug: 'executive-screening',
    tagline: 'Comprehensive screening for busy professionals',
    price: 399,
    discountPrice: 299,
    description: 'A comprehensive medical screening package addressing cardiovascular risks, metabolic status, and vitamin deficiencies.',
    features: [
      'All Essential Wellness Tests',
      'HbA1c (Three-month average blood glucose)',
      'Thyroid Profile (TSH, Free T3, Free T4)',
      'Vitamin D & Vitamin B12 Levels',
      'Electrocardiogram (ECG)',
      'Urine Analysis',
      'Detailed Cardiologist or Physician Review',
    ],
    idealFor: 'Professionals and individuals aged 35+ seeking a deeper health analysis.',
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-sarah-jenkins',
    name: 'Dr. Sarah Jenkins',
    title: 'MD, FACC',
    slug: 'dr-sarah-jenkins',
    departmentId: 'dept-cardiology',
    specialty: 'Interventional Cardiology',
    experienceYears: 16,
    education: [
      'Doctor of Medicine, Johns Hopkins University School of Medicine',
      'Cardiology Fellowship, Cleveland Clinic',
      'Residency in Internal Medicine, Massachusetts General Hospital',
    ],
    bio: 'Dr. Jenkins is a board-certified interventional cardiologist with over 15 years of experience. She specializes in minimally invasive catheter procedures to diagnose and treat coronary artery disease, valve defects, and congenital heart disorders.',
    availability: {
      days: ['Monday', 'Tuesday', 'Thursday'],
      slots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM'],
    },
    rating: 4.9,
    reviewCount: 312,
    languages: ['English', 'Spanish'],
    imageUrl: '/images/doctors/doc_female_1.png',
  },
  {
    id: 'doc-marcus-vance',
    name: 'Dr. Marcus Vance',
    title: 'MD, FAAP',
    slug: 'dr-marcus-vance',
    departmentId: 'dept-pediatrics',
    specialty: 'Pediatric Care',
    experienceYears: 12,
    education: [
      'Doctor of Medicine, Harvard Medical School',
      'Pediatric Residency, Boston Children\'s Hospital',
    ],
    bio: 'Dr. Vance is dedicated to providing compassionate healthcare to infants, children, and teens. He focuses heavily on preventive care, early childhood development, and immunizations.',
    availability: {
      days: ['Wednesday', 'Thursday', 'Friday'],
      slots: ['08:30 AM', '09:30 AM', '10:30 AM', '01:30 PM', '02:30 PM', '03:30 PM'],
    },
    rating: 4.85,
    reviewCount: 245,
    languages: ['English', 'French'],
    imageUrl: '/images/doctors/doc_male_1.png',
  },
  {
    id: 'doc-emily-carter',
    name: 'Dr. Emily Carter',
    title: 'MD',
    slug: 'dr-emily-carter',
    departmentId: 'dept-gen-med',
    specialty: 'Family Medicine',
    experienceYears: 14,
    education: [
      'Doctor of Medicine, Stanford University School of Medicine',
      'Residency in Family Medicine, UCSF Medical Center',
    ],
    bio: 'Dr. Carter provides comprehensive primary care for patients of all ages. She focuses on disease prevention, chronic illness management, lifestyle medicine, and general health education.',
    availability: {
      days: ['Monday', 'Wednesday', 'Friday'],
      slots: ['08:00 AM', '10:00 AM', '11:00 AM', '01:00 PM', '03:00 PM'],
    },
    rating: 4.92,
    reviewCount: 189,
    languages: ['English', 'Spanish'],
    imageUrl: '/images/doctors/doc_female_2.png',
  },
  {
    id: 'doc-michael-anderson',
    name: 'Dr. Michael Anderson',
    title: 'MD, FAAOS',
    slug: 'dr-michael-anderson',
    departmentId: 'dept-orthopedics',
    specialty: 'Orthopedic Surgery',
    experienceYears: 18,
    education: [
      'Doctor of Medicine, Columbia University Vagelos College of Physicians and Surgeons',
      'Orthopedic Surgery Residency, Hospital for Special Surgery, NY',
    ],
    bio: 'Dr. Anderson is an expert in joint reconstructive surgeries, sports medicine injuries, and complex fracture care. He employs muscle-sparing approaches for rapid rehabilitation and recovery.',
    availability: {
      days: ['Tuesday', 'Thursday', 'Friday'],
      slots: ['09:00 AM', '10:30 AM', '11:30 AM', '02:00 PM', '04:00 PM'],
    },
    rating: 4.88,
    reviewCount: 402,
    languages: ['English'],
    imageUrl: '/images/doctors/doc_male_2.png',
  },
  {
    id: 'doc-sophia-bennett',
    name: 'Dr. Sophia Bennett',
    title: 'MD, PhD',
    slug: 'dr-sophia-bennett',
    departmentId: 'dept-neurology',
    specialty: 'Clinical Neurology',
    experienceYears: 15,
    education: [
      'Doctor of Medicine and PhD in Neurosciences, Yale School of Medicine',
      'Neurology Fellowship, Mayo Clinic Graduate School of Medicine',
    ],
    bio: 'Dr. Bennett focuses on advanced neurology care. She has clinical expertise in treating stroke patients, managing epilepsy syndromes, chronic migraines, and peripheral nerve disorders.',
    availability: {
      days: ['Monday', 'Tuesday', 'Wednesday'],
      slots: ['10:00 AM', '11:00 AM', '01:30 PM', '03:00 PM', '04:30 PM'],
    },
    rating: 4.95,
    reviewCount: 215,
    languages: ['English', 'German'],
    imageUrl: '/images/doctors/doc_female_1.png',
  },
  {
    id: 'doc-olivia-martinez',
    name: 'Dr. Olivia Martinez',
    title: 'MD, FACOG',
    slug: 'dr-olivia-martinez',
    departmentId: 'dept-womens-health',
    specialty: 'Obstetrics & Gynecology',
    experienceYears: 11,
    education: [
      'Doctor of Medicine, NYU Grossman School of Medicine',
      'OB/GYN Residency, Brigham and Women\'s Hospital',
    ],
    bio: 'Dr. Martinez is passionate about comprehensive women\'s health. She specializes in maternal-fetal wellness, high-risk pregnancy plans, minimally invasive surgery, and menopause consultations.',
    availability: {
      days: ['Tuesday', 'Thursday'],
      slots: ['08:00 AM', '09:00 AM', '11:00 AM', '02:00 PM', '03:30 PM'],
    },
    rating: 4.87,
    reviewCount: 168,
    languages: ['English', 'Spanish'],
    imageUrl: '/images/doctors/doc_female_2.png',
  },
];

export const NAV_LINKS = [
  { label: 'Home',            href: '/' },
  { label: 'About',           href: '/about/' },
  { label: 'Services',        href: '/services/' },
  { label: 'Find a Doctor',   href: '/doctors/' },
  { label: 'Contact',         href: '/contact/' },
];

export const MOCK_BLOG_ARTICLES: BlogArticle[] = [
  {
    id: 'advances-modern-cardiology',
    title: 'Advances in Modern Cardiology: What Patients Should Know',
    summary: 'A comprehensive look at breakthrough cardiac treatments, minimally invasive procedures, and how advanced imaging is transforming heart disease management.',
    content: 'Cardiology has entered a golden age of digital diagnostic telemetry and minimally invasive interventions. Traditional open-heart surgeries are increasingly being replaced by transcatheter procedures like TAVR, which allow patients to return home within days instead of weeks. Furthermore, advanced multi-slice CT scanning and cardiac MRI provide clinical teams with highly detailed 3D maps of coronary arteries before any incisions are made. These tech-driven steps greatly reduce patient trauma and lead to better recovery curves.\n\nEarly warning detection is also evolving. Continuous remote monitoring patches can detect arrhythmias long before symptoms manifest. Patients at risk are empowered with active tracking tools that sync directly with their clinical dashboards, enabling preventive adjustments to medicine or lifestyle before an acute event arises.',
    category: 'Medical Tips',
    readTime: '8 min read',
    author: 'Dr. Emily Carter',
    date: 'July 5, 2026',
    image: '/images/blog/blog_cardiology.png',
    tags: ['Cardiology', 'Heart Health', 'Medical Research'],
    featured: true,
  },
  {
    id: 'future-digital-healthcare',
    title: 'The Future of Digital Healthcare: Telemedicine & AI Diagnostics',
    summary: 'How artificial intelligence, remote patient monitoring, and digital health platforms are reshaping the way healthcare is delivered globally.',
    content: 'The integration of Artificial Intelligence and high-definition telemedicine represents a massive paradigm shift in modern care delivery. Machine learning models can analyze diagnostic images like MRIs and CT scans in seconds, highlighting minute anomalies for radiologist review with outstanding precision. In rural or underserved communities, virtual clinics provide direct links to metropolitan specialists, bridging the physical care gap.\n\nRemote patient monitoring is another critical pillar. Wearable bio-sensors continuously track heart rate variability, blood oxygen, and respiratory patterns, streaming this data into secure clinical databases. If metrics deviate from baseline, the system alerts the medical team, allowing timely interventions that save lives.',
    category: 'Healthcare Technology',
    readTime: '6 min read',
    author: 'Dr. James Walker',
    date: 'July 3, 2026',
    image: '/images/blog/blog_digital_health.png',
    tags: ['Telemedicine', 'AI', 'Digital Health'],
    featured: false,
  },
  {
    id: 'understanding-preventive-medicine',
    title: 'Understanding Preventive Medicine: A Complete Patient Guide',
    summary: 'Why annual screenings, vaccinations, and lifestyle modification programs are your strongest defense against chronic disease and early mortality.',
    content: 'Preventive medicine is the most effective shield against chronic metabolic and cardiovascular disorders. Rather than treating diseases after they manifest, preventive care focuses on identifying risks early through routine panels, genetic profiling, and lifestyle tracking. Regular health checkups help detect hypertension, prediabetes, and early oncology markers when they are easiest to reverse.\n\nIn addition to medical screening, preventive medicine focuses heavily on active physical conditioning, sleep hygiene, and nutritional adjustments. By adopting personalized wellness frameworks, patients can significantly extend their healthspan and reduce lifetime dependency on complex medical treatments.',
    category: 'Preventive Care',
    readTime: '5 min read',
    author: 'Dr. Sophia Martinez',
    date: 'July 1, 2026',
    image: '/images/blog/blog_wellness.png',
    tags: ['Prevention', 'Screenings', 'Health Check'],
    featured: false,
  },
  {
    id: 'balanced-diet-benefits',
    title: 'The Benefits of a Balanced Diet: Evidence-Based Nutrition',
    summary: 'Clinical evidence on how a balanced macronutrient diet reduces cardiovascular risk, supports immunity, and promotes cognitive function across all life stages.',
    content: 'Nutritional science clearly demonstrates the direct link between balanced food intake and cellular health. A diet rich in leafy greens, healthy fats, lean proteins, and complex carbohydrates supports gut health and mitigates chronic low-grade inflammation. This, in turn, decreases the risk of cardiovascular plaque buildup and metabolic dysfunction.\n\nEstablishing a healthy eating pattern is not about restrictive deprivation, but about nourishing the body with diverse nutrients. Whole foods supply essential vitamins and minerals that bolster immune cell production and maintain cognitive clarity, providing sustained energy throughout the day.',
    category: 'Nutrition',
    readTime: '7 min read',
    author: 'Dr. David Morgan',
    date: 'June 28, 2026',
    image: '/images/blog/blog_nutrition.png',
    tags: ['Nutrition', 'Diet', 'Wellness'],
    featured: false,
  },
  {
    id: '10-daily-habits-healthier-life',
    title: '10 Daily Habits for a Healthier and Longer Life',
    summary: 'Evidence-backed micro-habits that have measurable impacts on metabolic health, cardiovascular fitness, and mental resilience when practiced consistently.',
    content: 'Longevity is strongly influenced by daily routines. Practicing consistent habits, like sleeping 7-8 hours, walking 10,000 steps, and drinking adequate water, significantly improves metabolic efficiency and vascular flexibility. Consistent hydration and physical movement support joint health and assist the body in regular detoxification.\n\nEqually important are mental wellness habits, such as mindfulness practices and screen-free routines before bed. Taking short breaks to reduce sensory overload lowers stress hormones like cortisol, helping protect the nervous system from chronic fatigue.',
    category: 'Wellness',
    readTime: '5 min read',
    author: 'Dr. Emily Carter',
    date: 'June 25, 2026',
    image: '/images/blog/blog_wellness.png',
    tags: ['Habits', 'Lifestyle', 'Wellness'],
    featured: false,
  },
  {
    id: 'reduce-heart-disease-risk',
    title: 'How to Reduce Your Risk of Heart Disease',
    summary: 'Practical, physician-reviewed steps for managing blood pressure, cholesterol, body weight, and stress to significantly reduce your lifetime cardiac risk.',
    content: 'Preventing heart disease requires active lifestyle management and routine monitoring. Managing blood pressure and cholesterol levels through a sodium-conscious diet and aerobic conditioning keeps arteries clear and flexible. Engaging in 150 minutes of moderate exercise weekly strengthens the heart muscle and improves circulation.\n\nControlling stress is also essential for cardiac health. High stress levels trigger adrenaline releases that raise heart rate and blood pressure, straining the cardiovascular system. Practicing relaxation techniques and maintaining regular checkups helps minimize these risks effectively.',
    category: 'Medical Tips',
    readTime: '6 min read',
    author: 'Dr. James Walker',
    date: 'June 22, 2026',
    image: '/images/blog/blog_cardiology.png',
    tags: ['Heart Disease', 'Prevention', 'Cardiology'],
    featured: false,
  },
  {
    id: 'recognizing-diabetes-symptoms',
    title: 'Recognizing Early Symptoms of Diabetes',
    summary: 'Early warning signs of Type 1 and Type 2 diabetes that patients often overlook, and why prompt diagnosis makes a critical difference in long-term outcomes.',
    content: 'Early detection of diabetes is crucial to preventing long-term nerve, kidney, and cardiovascular damage. Subtle symptoms like increased thirst, frequent urination, unexplained weight changes, and persistent fatigue should not be ignored. These signs indicate the body is struggling to manage blood glucose levels efficiently.\n\nIf you experience these warning signs, a simple HbA1c test can determine your glycemic status. Early lifestyle adjustments, such as carbohydrate control and active fitness plans, can often reverse prediabetes and prevent full onset, ensuring stable metabolic health.',
    category: 'Medical Tips',
    readTime: '4 min read',
    author: 'Dr. Sophia Martinez',
    date: 'June 20, 2026',
    image: '/images/blog/blog_wellness.png',
    tags: ['Diabetes', 'Diagnosis', 'Prevention'],
    featured: false,
  },
  {
    id: 'superfoods-heart-health',
    title: 'Superfoods for Heart Health: A Nutritionist\'s Guide',
    summary: 'Clinical evidence behind omega-3 rich foods, antioxidant-dense berries, leafy greens, and whole grains in reducing LDL cholesterol and arterial inflammation.',
    content: 'Certain nutrient-dense foods offer exceptional support for cardiac function and vascular health. Superfoods like salmon, walnuts, chia seeds, and berries are packed with omega-3 fatty acids and antioxidants. These compounds reduce triglycerides, lower blood pressure, and combat arterial plaque buildup.\n\nIncorporating leafy greens, olive oil, and whole grains into your daily meals further supports cardiovascular health. Rich in dietary fiber and essential minerals like potassium, these foods help maintain optimal blood flow and keep inflammation at bay, promoting long-term vitality.',
    category: 'Nutrition',
    readTime: '5 min read',
    author: 'Dr. David Morgan',
    date: 'June 18, 2026',
    image: '/images/blog/blog_nutrition.png',
    tags: ['Superfoods', 'Nutrition', 'Heart Health'],
    featured: false,
  },
];


